

services:
  web:
    build: .
    container_name: sistema-venta-web
    ports:
      - "8082:80"
    volumes:
      - ./:/var/www/html

    depends_on:
      - db
    environment:
      - MYSQL_HOST=db
      - MYSQL_USER=root
      - MYSQL_PASSWORD=12345
      - MYSQL_DATABASE=sistema

  db:
    image: mariadb:11.8.1-rc
    container_name: sistema-venta-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 12345
      MYSQL_DATABASE: sistema
    volumes:
      - ./mysql_data:/var/lib/mysql
      - ./:/docker-entrypoint-initdb.d  
